INSERT INTO `perils` (`insurance_type_id`, `title`) VALUES
(1, 'Accidental damages caused by external means'),
(1, 'Fire, explosion, implosions, self-ignition, lightning'),
(1, 'Flood'),
(1, 'Typhoon'),
(1, 'Hurricane'),
(1, 'Storm'),
(1, 'Tempest'),
(1, 'Inundation'),
(1, 'Cyclone'),
(1, 'Hailstorm'),
(1, 'Frost'),
(1, 'Whilst in transit by road, rail, inland waterway, air, lift or elevator'),
(1, 'Act of terrorism'),
(1, 'Riot and strike, malicious damage'),
(1, 'Burglary, theft, housebreaking'),
(1, 'Earthquakes (fire & shock damage)'),
(1, 'Landslide & rockslide'),
(1, 'Death or bodily injury to a third party'),
(1, 'Damage to a third party property'),
(1, 'Accidental death of the vehicles owner or driver'),
(1, 'Permanent total disability suffered by the vehicle owner or driver'),
(2, 'Fire and smoke'),
(2, 'Lightning strikes'),
(2, 'Windstorms and hail'),
(2, 'Explosion'),
(2, 'Vandalism and malicious mischief'),
(2, 'Damage from an aircraft, car or vehicle'),
(2, 'Theft'),
(2, 'Falling objects'),
(2, 'Weight of ice, snow or sleet'),
(2, 'Water damage'),
(4, 'Emergency Medical Insurance'),
(4, 'Emergency Medical Evacuation'),
(4, 'Accidental Death & Dismemberment'),
(4, 'Lost/Stolen Luggage'),
(4, 'Rental Car Coverage'),
(4, 'Hotel/Cruise Ship Protection'),
(4, 'Trip Cancellation'),
(4, 'Trip Interruption'),
(4, 'Flight Cancellation/Travel Delay'),
(4, 'Supplier Bankruptcy'),
(7, 'Perils of Sea'),
(7, 'Fire'),
(7, 'Man-of-War'),
(7, 'Enemies'),
(7, 'Pirates, Rovers, Thieves'),
(7, 'Jettison'),
(7, 'Barratry'),
(7, 'Restraints and Detainments'),
(7, 'The Free of Capture and Seizure Clause (F.C. & S. Clause)'),
(7, 'Explosion'),
(7, 'Strikes, Riots and Civil Commotion Clause');